#!/bin/bash
echo

pow=$1
path=$2
beep="$path/beep.mp3"

good_signal()
{
	if [[ $pow > 210 ]];then
		echo "signal power 4/4"
		for i in {1..4}; do
			printf "."
			ffmpeg -i $beep -f alsa default &>/dev/null
			sleep 0.1
		done
	elif [[ $pow < 210 ]] && [[ $pow > 190 ]];then
		echo "signal power 3/4"
		for i in {1..3}; do 
			printf "."
			ffmpeg -i $beep -f alsa default &>/dev/null
			sleep 0.3
		done
	elif [[ $pow < 190 ]] && [[ $pow > 150 ]];then
		echo "signal power 2/4"
		for i in {1..2}; do 
			printf "."
			ffmpeg -i $beep -f alsa default &>/dev/null
			sleep 0.5
		done
	fi
}
if [[ $pow > 150 ]] ;then 
	good_signal
	echo
	exit 
fi
