#!/bin/bash

FFM_CMD='ffmpeg -i $beep -f alsa "plughw:CARD=Intel,DEV=0"'
PRG_NAME="wbeep"
IFACE=$1
SSID=$2
LIST_CMD="${PWD}/list_ssid"
SCAN_CMD="${PWD}/scan_ssid"
beep="${PWD}/beep.mp3"

wbeep_depends()
{
	if [[ $(type $@ &>/dev/null; echo $?) = 0 ]]; then
		return 0 
	else 
		return 1
	fi
}
wbeep_die()
{
	text=$1
	printf "$PRG_NAME: $text \n"
	exit 1
}
wbeep_sig()
{
	printf "\nquit!\n"
	exit 0
}
wbeep_good_signal()
{
	pow=$1
	path=$2

	if [[ $pow > 210 ]];then
		echo "signal power 4/4"
		for i in {1..4}; do
			printf "."
			$FFM_CMD &>/dev/null
			sleep 0.1
		done
	elif [[ $pow < 210 ]] && [[ $pow > 190 ]];then
		echo "signal power 3/4"
		for i in {1..3}; do 
			printf "."
			$FFM_CMD &>/dev/null
			sleep 0.3
		done
	elif [[ $pow < 190 ]] && [[ $pow > 150 ]];then
		echo "signal power 2/4"
		for i in {1..2}; do 
			printf "."
			$FFM_CMD &>/dev/null
			sleep 0.5
		done
	fi
}
wbeep_usage()
{
		printf "
Usage: $PRG_NAME [INTERFACE] [SSID]
	example: sudo $PROG_NAME wlan0 tplink-123
or
Usage: $PRG_NAME [INTERFACE] [OPTION]
	example: sudo $PRG_NAME wlan0 -l

OPTIONS
	-l, --list : to show list ssids
"
	exit 1

}
trap wbeep_sig SIGINT SIGTERM SIGQUIT


main()
{

case $2 in
	-l | --list)
		$LIST_CMD $IFACE
		exit 0
		;;
	*)
		wbeep_usage
		;;
esac

while true; do
	printf "packet sent ..."
	cmd=$($SCAN_CMD $IFACE $SSID)
	
	sig=$(echo $cmd | awk '{ print $5 }')
	if [[ $sig < 150 ]] ;then
		printf "\nsignal pwer 1/4\n"
		printf "."
		$FFM_CMD &>/dev/null
		echo
	else
		wbeep_good_signal $sig ${PWD}
		echo
	fi
done	
}

if [[ $1 = "--help" ]] || [[ ! $1 ]] ;then
	wbeep_usage 
fi

if [[ ! $UID = 0 ]]; then
	wbeep_die "run script as root : Permission denied"
else
	wbeep_depends ${SCAN_CMD} ${LIST_CMD} || \
		wbeep_die "missing requirements $(basename -a ${SCAN_CMD} ${LIST_CMD} | tr "\n" " ")\n\
you can see README.md for more information"

	main $@
fi


